spring:
  application:
    name: airline-service
  config:
    import: optional:docker.env[.properties]

  #Configuration data sources
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      data-source-properties:
        stringtype: unspecified
  jpa:
    open-in-view: true

  #Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yaml
    default-schema: ${LIQUIBASE_SCHEMA}

  #Kafka
  kafka:
    bootstrap-servers: ${KAFKA_HOST}:9092

server:
  port: 0

eureka:
  client:
    service-host: ${EUREKA_HOST}
    service-url:
      defaultZone: http://${eureka.client.service-host}:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${EUREKA_HOST}
